[build]
  command = "yarn run lambda:build"
  functions = "./dist-lambda/"

# We only use lambdas in this repo, so we redirect the actual root to the search
# website
[[redirects]]
  from = "/"
  to = "https://gamemaster.pixelastic.com/society/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Clacks-Overhead = "GNU Terry Pratchett"
