version: 2
_aliases:
  - &defaults
    docker:
      - image: circleci/node:12.12.0
  - &restore_cache
    restore_cache:
      key: yarn-cache-{{ checksum "yarn.lock" }}
  - &yarn_install
    run: 'yarn install'
  - &save_cache
    save_cache:
      key: yarn-cache-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn

jobs:
  ci:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *yarn_install
      - *save_cache
      - run: 'yarn run ci'
  weeklyUpdate:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *yarn_install
      - *save_cache
      - run: 'yarn run ci:weeklyUpdate'

workflows:
  version: 2
  commit:
    jobs:
      - ci:
          filters:
            branches:
              ignore: /^wip\/.*/

  weeklyUpdate:
    jobs:
      - weeklyUpdate:
          filters:
            branches:
              only: wip/circleci
