version: 2

# Aliases, so we can reference them in our jobs to avoid duplication of code
_aliases:
  - &defaults
    docker:
      - image: circleci/node:12.12.0
  - &restore_cache
    restore_cache:
      key: yarn-cache-{{ checksum "yarn.lock" }}
  - &yarn_install
    run: 'yarn install'
  - &save_cache
    save_cache:
      key: yarn-cache-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn

# Our list of jobs, so we can reference them in our worflows
jobs:
  # This will attempt to build/test/lint, to check that the code is in good
  # shape
  ci:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *yarn_install
      - *save_cache
      - run: 'yarn run ci'
  # This will recrawl the wiki, commit changes to the data.json and file and
  # submit a PR for approval of the changes
  weeklyUpdate:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *yarn_install
      - *save_cache
      - run: 'yarn run ci:weeklyUpdate'

workflows:
  version: 2
  # On every commit and PR: run the build/test/lint checks
  commit:
    jobs:
      - ci
  # Every week: Recrawl the wiki and submit a PR with the changes
  weeklyUpdate:
    triggers:
      - schedule:
          cron: '0 9 * * 2'
          filters:
            branches:
              only:
                - master
    jobs:
      - weeklyUpdate
