name: Weekly publish

on:
  push:
    branches:
      - actions

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install -g yarn
      - run: yarn run test
