name: Weekly publish

on:
  push:
    branches:
      - actions

jobs:
  main:
    name: Regenerate data
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # GITHUB_USER: Pixelastic
      # GITHUB_EMAIL: tim@pixelastic.com
    steps:
      - uses: actions/checkout@v1
      - uses: geertvdc/setup-hub@master
      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: '12.x'
      # - name: Bootstrap repo
      #   run: |
      #     npm install -g yarn
      #     yarn install

      - name: Configure git
        run: |
          # git config user.name "${USER}"
          # git config user.email "${GITHUB_EMAIL}"
          # # git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          # git remote set-url origin https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

      - name: Show git config
        run: git config --list

      - name: Show ENV variables
        run: set | grep "GITHUB_"

      # - name: Regenerate file
      #   run: yarn run regenerate

      # - name: Commit the file
      #   run: |
      #     CURRENT_DATE=$(date +%F); git commit -am "chore(update): Weekly update ($CURRENT_DATE)"

      - name: Attempt a push
        run: |
          CURRENT_DATE=$(date +%F)
          BRANCH_NAME="weekly-$CURRENT_DATE"
          git checkout -b $BRANCH_NAME
          date > date.txt
          git add .
          git commit \
            --message "chore(update): Weekly update ($CURRENT_DATE)"
          hub pull-request \
            --push \
            --reviewer pixelastic \
            --message "Weekly update ($CURRENT_DATE)" \
            --message "Full message"

      # - name: Push it back
      #   run: git push origin master

      # Commit the file
      # yarn run release patch
