name: Weekly publish

on:
  push:
    branches:
      - actions

jobs:
  main:
    name: Regenerate data
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BRANCH_NAME: "weeklyUpdate"
    steps:
      - uses: actions/checkout@v1
      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: geertvdc/setup-hub@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Bootstrap repo
        run: |
          npm install -g yarn
          yarn install

      - name: Regenerate file
        run: yarn run regenerate

      - name: Check for changes
        # git diff exits with 0 if same files and 1 if different
        # We need to stop if it's the same file, so we negate the exit code
        run: '! git diff --quiet'

      - name: Commit the changed file
        if: success()
        run: |
          CURRENT_DATE=$(date +%F)
          git checkout -b $BRANCH_NAME
          git add ./lib/data.json
          git commit \
            --message "chore(update): Weekly update ($CURRENT_DATE)" \
            --message "This is an automated commit"

      - name: Create the Pull Request
        if: success()
        run: |
          git push --no-verify --set-upstream origin $BRANCH_NAME
          hub pull-request \
            --no-edit \
            --reviewer pixelastic \

      # - name: Push it back
      #   run: git push origin master

      # Commit the file
      # yarn run release patch
