name: Weekly publish

on:
  push:
    branches:
      - actions

jobs:
  main:
    name: Regenerate data
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: '12.x'
      # - name: Bootstrap repo
      #   run: |
      #     npm install -g yarn
      #     yarn install

      - name: Configure git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "tim@pixelastic.com"
          git remote set-url origin "git@github.com:${GITHUB_REPOSITORY}.git"

      - name: Show git config
        run: git config --list

      - name: Show ENV variables
        run: set | grep "GITHUB_"

      # - name: Regenerate file
      #   run: yarn run regenerate

      # - name: Commit the file
      #   run: |
      #     CURRENT_DATE=$(date +%F); git commit -am "chore(update): Weekly update ($CURRENT_DATE)"

      - name: Attempt a push
        run: |
          CURRENT_DATE=$(date +%F)
          BRANCH_NAME="weekly-$CURRENT_DATE"
          git checkout -b $BRANCH_NAME
          date > date.txt
          git add .
          git commit -m "chore(update): Weekly update ($CURRENT_DATE)"
          git push --set-upstream origin $BRANCH_NAME

      # - name: Push it back
      #   run: git push origin master

      # Commit the file
      # yarn run release patch
