name: Weekly publish

on: 
  schedule:
    - cron: 0 9 * * TUE

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: npm install, build, and test
        run: |
          npm run regenerate
          git commit -am "Weekly update"
